Ocean AKS 2.0 Implementation
spotinst/spotinst-sdk-python pull request #142
Opened 2023-09-22 06:25 UTC by pripatra

_This is the default pull request template. You can customize it by adding a `pull_request_template.md` at the root of your repo or inside the `.github` folder._

# Jira Ticket
https://spotinst.atlassian.net/browse/SPOTAUT-14452

_Include a link to your Jira Ticket_
_Example: [JIRAISS-1234](https://spotinst.atlassian.net/browse/JIRAISS-1234)_

# Demo

_Please add a recording of the feature/bug fix in work. if you added new routes, the recording should show the request and response for each new/changed route_

# Checklist:
- [ ] I have filled relevant self assessment ([NodeJS](https://docs.google.com/forms/d/e/1FAIpQLSfl14u9AOBAmxVJ272tvO7XNuXE-EMvWaGcaRZalu1UAKB7RA/viewform), [Frontend](https://docs.google.com/forms/d/e/1FAIpQLSdiBPNKH81w_EkavihVL8Uwb0j7tP8PwJmLFYm2nCOQxz-1qw/viewform), [Backend](https://docs.google.com/forms/d/e/1FAIpQLSed_PsTJ5-XIWkFL6BSDE2AQRBVPmwc3PAmHZkUn-erzVI37Q/viewform?usp=sf_link))
- [ ] I have run ESlint on my changes and fixed all warnings and errors (**NodeJS & Frontend Services**)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have validated all the requirements in the Jira task were answered
- [ ] I have all neccessary approvals for the design/mini design of this task
- [ ] I have approved the API changes and granular permission patterns (documentation subtask) (**For public services only**)

2023-09-22 11:45 UTC, ramrutha497 requested changes

2023-09-22 11:45 UTC, ramrutha497 commented on spotinst_sdk2/clients/ocean/__init__.py
> +
Divide into regions. Take reference to elastigroup client

2023-09-22 11:45 UTC, ramrutha497 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +
Divide into regions. Take reference to ocean aws model

2023-09-22 11:45 UTC, ramrutha497 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    '''
uniformly use """ """ for doc strings

2023-09-22 11:45 UTC, ramrutha497 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    max_scale_down_percentage: int
mark datatype as number double
(float)

2023-09-22 11:45 UTC, ramrutha497 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    max_gpu: int
mark datatype as number double for max and min gpu
(float)

2023-09-22 11:45 UTC, ramrutha497 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    availabilty_zones: List[str]
change to **availability**_zones

2023-09-22 11:45 UTC, ramrutha497 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    preferred_lifecycle: str
Add enum class
<html>
<body>
<!--StartFragment-->

preferredLifecycle | stringEnum: "Spot" "Regular"The preferred life cycle to launch the node. If not specified, the life cycle is chosen accoring to the scaled VNG.
-- | --


<!--EndFragment-->
</body>
</html>

2023-09-22 11:45 UTC, ramrutha497 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    does_not_exist = "doesNotExist"
please check the enum value. 
Given as "notExists" in docs

2023-09-22 11:45 UTC, ramrutha497 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +            conditions: Conditions = none):
declare scope: Scope = none

2023-09-22 13:31 UTC, ramrutha497 requested changes

2023-09-22 13:31 UTC, ramrutha497 commented on spotinst_sdk2/clients/ocean/__init__.py
> +    def get_all_ocean_vng(self):
Ocean id path param is missing.

2023-09-22 13:31 UTC, ramrutha497 commented on spotinst_sdk2/clients/ocean/__init__.py
> +        # Returns
Define arguments in the doc string

2023-09-22 13:31 UTC, ramrutha497 commented on spotinst_sdk2/clients/ocean/__init__.py
> +
Define arguments in doc string

2023-09-22 13:31 UTC, ramrutha497 commented on spotinst_sdk2/clients/ocean/__init__.py
> +
Get Cluster Aggregated Detailed Costs
Get Cluster Aggregated Summary Costs

Please implement these APIs. Comment here if there is a reason for not implementing the same

2023-09-24 18:28 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +class OceanAKS:
Rename this to 'Aks'

2023-09-24 18:33 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +class Labels:
This doesn't seem correct.

2023-09-24 18:34 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    os_disk_size_gB: int
Change parameter to os_disk_size_g_b

2023-09-24 18:35 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    os_sKU: OsSKU
change parameter to os_s_k_u

2023-09-24 18:36 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    fallback_to_oD: bool
parameter case, doesn't seem correct.

2023-09-24 18:37 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +class Architectures(Enum):
Change to "Architecture"

2023-09-24 18:38 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +class VmTypes(Enum):
change to "VmType"

2023-09-24 18:39 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    architectures: List[Architectures]
As per documentation, it is string, please confirm.

2023-09-24 18:39 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    max_memory_giB: float
change to "max_memory_gi_b"

2023-09-24 18:40 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    min_memory_giB: float
change to "min_memory_gi_b"

2023-09-24 18:40 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    min_vCpu: int
change to min_v_cpu

2023-09-24 18:41 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    min_nICs: int
change to min_n_i_cs

2023-09-24 18:42 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    max_vCpu: int
change to max_v_cpu

2023-09-24 18:59 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +class LaunchNewNodes:
Move this to LaunchNewNodesRequest region

2023-09-24 21:05 UTC, anuragsharma-123 commented on spotinst_sdk2/clients/ocean/__init__.py
> +    def get_all_ocean_cluster(self):
rename to get_all_ocean_clusters()

2023-09-24 21:08 UTC, anuragsharma-123 commented on spotinst_sdk2/clients/ocean/__init__.py
> +    def import_cluster_config(self, aks_cluster_name: str, resource_group_name: str):
Rename to import_cluster_configuration()

2023-09-24 21:12 UTC, anuragsharma-123 commented on spotinst_sdk2/clients/ocean/__init__.py
> +        response = self.send_post(
should use send_post_with_params()

2023-09-24 21:14 UTC, anuragsharma-123 commented on spotinst_sdk2/clients/ocean/__init__.py
> +    def get_all_ocean_vng(self):
Rename to get_all_ocean_vngs()

2023-09-24 21:18 UTC, anuragsharma-123 commented on spotinst_sdk2/clients/ocean/__init__.py
> +        List the configurations for all Ocean VNGs in the specified account.
1. This should support ocean_id to return VNGs in a specified cluster.
2.  The documentation also need to be corrected.

2023-09-24 21:21 UTC, anuragsharma-123 commented on spotinst_sdk2/clients/ocean/__init__.py
> +        Import cluster configuration of an AKS cluster to use in create_ocean_cluster api call
Documentation incorrect.

2023-09-24 21:21 UTC, anuragsharma-123 commented on spotinst_sdk2/clients/ocean/__init__.py
> +    def import_vng_config(self, node_pool_name: str, ocean_id: str):
Rename to import_vng_configuration()

2023-09-24 21:22 UTC, anuragsharma-123 commented on spotinst_sdk2/clients/ocean/__init__.py
> +        response = self.send_post(
Should use send_post_with_params call.

2023-09-24 21:23 UTC, anuragsharma-123 commented on spotinst_sdk2/clients/ocean/__init__.py
> +    def launch_new_nodes(self, body: azure_ocean.LaunchNewNodes):
rename "body" parameter to node_config

2023-09-24 21:39 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    min_memory_giB_per_node: float
should be min_memory_gi_b_per_node

2023-09-24 21:40 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    vngIds: List[str]
Variable name should be vng_ids

2023-09-24 21:43 UTC, anuragsharma-123 commented on spotinst_sdk2/clients/ocean/__init__.py
> +        response = self.send_get(
Should use send_get_with_params()

2023-09-24 21:45 UTC, anuragsharma-123 commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    all_matches:  List[Attribute]
should be all_match as per the schema

2023-09-25 06:16 UTC, pripatra commented on spotinst_sdk2/clients/ocean/__init__.py
> +
done

2023-09-25 07:54 UTC, pripatra commented on spotinst_sdk2/clients/ocean/__init__.py
> +    def get_all_ocean_vng(self):
not needed for list vngs call

2023-09-25 09:56 UTC, pripatra commented on spotinst_sdk2/models/ocean/azure/__init__.py
> +    architectures: List[Architectures]
type is enum so have implemented like this

2023-09-25 10:56 UTC, pripatra commented on spotinst_sdk2/clients/ocean/__init__.py
> +        response = self.send_get(
function doesn't exist

2023-09-26 07:02 UTC, anuragsharma-123 approved these changes

2023-09-26 07:03 UTC, ramrutha497 approved these changes

2023-09-26 07:03 UTC, anuragsharma-123 approved these changes

2023-09-26 07:03 UTC, merged